### ISSUE TITLE
Testing universal2 wheel on arm64 macOS cp38 runner result in `not a supported wheel on this platform`

### ISSUE THREAD

**Issue by laggykiller** [pypa/cibuildwheel#1767] opened 2024-02-27 09:01 UTC
### Description

Currently, to test a wheel, wheels are first installed with pip. On arm64 macOS github runner (`macos-14`), wheels are installed with `arch -x86_64 pip install ...`. This results in `ERROR: xxx_universal2.whl is not a supported wheel on this platform.`.

On my local M1 macmini, I am able to recreate the issue by:
1. Install python3.8.10 x86_64 version from (Note that x86_64 version is used in python3.8 even for arm64 macOS runner according to https://github.com/pypa/cibuildwheel/pull/1169): https://www.python.org/ftp/python/3.8.10/python-3.8.10-macosx10.9.pkg
2. `python3.8 -m pip install apngasm_python-1.2.3-cp311-cp311-macosx_11_0_universal2.whl`.

If I rename the problematic wheel name to `-macosx_10_9_universal2.whl`, the problem does not occur. This does not make sense as we are testing on macos-14, which is much newer than macos `10.9` or `11.0`.

This problem does not occur for universal2 python versions (i.e. python >3.8).

Relevant issue: https://github.com/pypa/cibuildwheel/issues/1746

You can download sample universal2 wheels from artifact of this run (https://github.com/laggykiller/apngasm-python/actions/runs/8063189658), or directly down here:

[apngasm_python-1.3.0-cp38-cp38-macosx_11_0_universal2.whl.zip](https://github.com/pypa/cibuildwheel/files/14428754/apngasm_python-1.3.0-cp38-cp38-macosx_11_0_universal2.whl.zip)
[apngasm_python-1.3.0-cp39-cp39-macosx_11_0_universal2.whl.zip](https://github.com/pypa/cibuildwheel/files/14428755/apngasm_python-1.3.0-cp39-cp39-macosx_11_0_universal2.whl.zip)
[apngasm_python-1.3.0-cp310-cp310-macosx_11_0_universal2.whl.zip](https://github.com/pypa/cibuildwheel/files/14428756/apngasm_python-1.3.0-cp310-cp310-macosx_11_0_universal2.whl.zip)
[apngasm_python-1.3.0-cp311-cp311-macosx_11_0_universal2.whl.zip](https://github.com/pypa/cibuildwheel/files/14428757/apngasm_python-1.3.0-cp311-cp311-macosx_11_0_universal2.whl.zip)
[apngasm_python-1.3.0-cp312-abi3-macosx_11_0_universal2.whl.zip](https://github.com/pypa/cibuildwheel/files/14428758/apngasm_python-1.3.0-cp312-abi3-macosx_11_0_universal2.whl.zip)

(`.zip` was added to the end of whl file name end so that github allow me to upload it. Just remove `.zip` extension from the file name after downloading.)

### Build log

https://github.com/laggykiller/apngasm-python/actions/runs/8061744757/job/22020065912#step:4:1347

EDIT: I have tried with cibuildwheel master branch, and the problem still exists: https://github.com/laggykiller/apngasm-python/actions/runs/8074988563/job/22061164760#step:4:1419

### CI config

https://github.com/laggykiller/apngasm-python/blob/c046caa64b633fe1cc957f67fd4fbc0f6abd7b40/.github/workflows/build.yml

**Comment by laggykiller** [comment] 2024-02-28 05:40
As I investigate further, it seems like the problem is caused by x86_64 (non-universal2) version of python 3.8 running on arm64 macOS, which has bug in checking wheel tag such that `*-macosx_11_universal2.whl` is misrecognized as invalid.

This seems to be caused by the same issue as https://github.com/pypa/cibuildwheel/issues/1603 and I can confirm that adding `SYSTEM_VERSION_COMPAT=0` would allow the wheel to be installed

Should we add `SYSTEM_VERSION_COMPAT=0` for the user in cibuildwheel during pip install wheel?

Other hacks, workarounds:
- Use universal2 python3.8, but as discussed in https://github.com/pypa/cibuildwheel/pull/1169 it would increase the minimum MacOS version for the x86_64 arch from 10.9 to 11.0, so this is probably no go.
- Install universal2 python3.8 in CI ourselves as suggested in https://github.com/pypa/cibuildwheel/pull/1169#issuecomment-1923705411
- Change deployment target of wheel to <11.0 instead of >=11.0
- Skip testing py38 universal2 wheel

**Comment by joerick** [comment] 2024-02-28 12:00
Nice work debugging this. So you'll be hitting this error due to these lines in your config:

https://github.com/laggykiller/apngasm-python/blob/c046caa64b633fe1cc957f67fd4fbc0f6abd7b40/.github/workflows/build.yml#L75-L76

Is there a specific reason you set MACOSX_DEPLOYMENT_TARGET to 11.0 on this build? It's 10.15 on the x86_64 one. macOS 11.0 is the first to support arm64, so it's implicit that you'd need 11.0 or later on arm64.

(Also, just FYI, unless there's something going on here that I've missed, you shouldn't need to set `_PYTHON_HOST_PLATFORM` yourself, cibuildwheel [will do that for you](https://github.com/pypa/cibuildwheel/blob/main/cibuildwheel/macos.py#L247-L260).)

As for the broader issue, I think you're right, we should set SYSTEM_VERSION_COMPAT=0 when testing universal2 Python 3.8 wheels on x86_64. Otherwise, as you have discovered, it's not possible to set MACOSX_DEPLOYMENT_TARGET to anything greater than 10.16. I don't think that Python 3.9+ would need this though, because they'll be built with a newer SDK, so macOS won't do any version-compat shimming. I see that you only had the issue with 3.8, so I guess that's correct.

**Comment by joerick** [comment] 2024-02-28 17:00
For reference, this is really a bug in pip that we're working around, ref https://github.com/pypa/pip/issues/11715

**Comment by joerick** [comment] 2024-03-03 11:08
To be clear, this is a dupe of https://github.com/pypa/cibuildwheel/issues/1603 , i'm just more inclined to do something about it given that a fix in pip doesn't appear to be imminent...

**Closed** 2024-03-11 01:36 UTC

**Comment by bdarnell** [comment] 2024-06-04 16:41
My builds are producing warnings that link to this issue. ([sample build](https://github.com/tornadoweb/tornado/actions/runs/9368928993)) Is any action required? (If not, is the log message necessary?)  Does this mean that users of my package will have to use SYSTEM_VERSION_COMPAT=0 for py38 on macos?

Note that I am not setting MACOS_DEPLOYMENT_TARGET unless cibuildwheel is doing it for me somewhere.
