### ISSUE TITLE
Expose major version branch for use with GitHub actions

### ISSUE THREAD

**Issue by wjakob** [pypa/cibuildwheel#1383] opened 2022-12-29 14:12 UTC
### Description

I use cibuildwheel and dependabot across a few projects. Whenever cibuildwheel makes a minor patch-level change, this creates tons of PRs of the form`Bump pypa/cibuildwheel from 2.11.1 to 2.11.4` that I don't care for (and which cause days of computation time just to run the CI suite).

I would love to reference cibuildwheel using *coarser* version specifiers, but this does not work. For example, when I write

```
- uses: pypa/cibuildwheel@v2
```

in a GHA file, the build fails with the following error message:

```
Error: Unable to resolve action `pypa/cibuildwheel@v2`, unable to find version `v2`
```

It would be lovely if cibuildwheel was installable in this way. Thanks!

**Comment by joerick** [comment] 2023-01-17 09:22
Duplicate of #1358 and #1243. The TLDR is that we don't follow semver (it wouldn't be feasible for this project), and since builds are a crucial step of a release process, as maintainers we don't think it's a good idea. 

That said, it's a common request so if there's a way to automate it from Github releases I'd be okay with offering the tag, and just not publicising it.

**Closed by joerick** 2023-01-17 09:22 UTC
