### ISSUE TITLE
Built wheel file name should match package name and not replace dashes with underscores

### ISSUE THREAD

**Issue by ketozhang** [pypa/cibuildwheel#1289] opened 2022-09-28 02:56 UTC
### Description

Dashes are being replaced with underscores. Dashes are valid package names ([PEP 503](https://peps.python.org/pep-0503/)).

The results issue does not exist with the `build` tool (`python -m build --wheel`).

```toml
# pyproject.toml
[project]
name="redacted-package-name"
```

### Build log

```
$ cibuildwheel --platform linux --output-dir dist/
...
Created wheel for redacted-package-name: filename=redacted_package_name-1.0.0-cp310-cp310-linux_x86_64.whl size=1191321 sha256=b9c8fc1ebc75dbc844a81565372aa57ea66de38f2dd1c22e8a1e694ade01387f
...
```

**Comment by henryiii** [comment] 2022-09-28 03:16
Duplicate of #1288. Incorrect, nothing can parse or load your wheel if it used dashes, since they are used for the tags. Only sdists support dashes (and some build backends may still normalize to underscores). And this is done by the build backend (setuptools, hatchling, flit, poetry, etc), not us or build.

**Closed by henryiii** 2022-09-28 03:16 UTC

**Comment by ketozhang** [comment] 2022-09-28 16:35
Apologies for the duplicate (not sure how that happened)! 
You're right, build is consistent with cibuildwheel. I must've misread the file names with sdist.
