### ISSUE TITLE
Getting the (future) build information from while building

### ISSUE THREAD

**Issue by AlmogBaku** [pypa/cibuildwheel#1124] opened 2022-06-04 19:30 UTC
### Description

Is there a way to expose the build architecture and platform while building(maybe via environment variable?

About my use case:
I'm building an extension with Golang, and I want to specify the arch for the go toolchain
You can see my source code here: https://github.com/natun-ai/pysdk/blob/master/setup.py

**Comment by joerick** [comment] 2022-06-17 18:44
Duplicate of #944.

**Closed by joerick** 2022-06-17 18:44 UTC

**Comment by AlmogBaku** [comment] 2022-06-21 22:30
If anyone is interested - With GH Actions, I solved it by exposing the information encoded as base64 in the environment variable:
https://github.com/natun-ai/labsdk/blob/master/.github/workflows/release.yaml
