### ISSUE TITLE
Likely bug in cibuildwheel

### ISSUE THREAD

**Issue by mathias-von-ottenbreit** [pypa/cibuildwheel#1983] opened 2024-08-24 11:08 UTC
### Description

Please look at [this](https://github.com/actions/runner-images/issues/10461#issuecomment-2308250945) issue which was originally thought to be a bug in Github Actions. However, it seems that a bug in cibuildwheel was introduced in v2.18.0.

**Comment by henryiii** [comment] 2024-08-28 04:01
Are you sure it's not a bug in setuptools? IIRC that was a bug for a bit there?

**Comment by jepler** [comment] 2024-09-17 16:05
I'm also seeing `'NoneType' object is not subscriptable` causing various builds to fail. For me, this was first seen in https://github.com/adafruit/g722_1_mod/pull/27 " Bump pypa/cibuildwheel from 2.20.0 to 2.21.1", however when re-running the workflow on my main branch (so cibuildwheel 2.20.0) the same failure occurs. This would seem to imply that the problem is elsewhere than cibuildwheel, or is an interaction that also depends on the version of some other package.

For me, many builds succeed, but for example PyPy 3.8 manylinux x86_64 fails. The failure on macos is also PyPy 3.8 (PyPy 3.8 macOS x86_64). However, windows pypy 3.8 succeeds!

The error seems to indicate that detection of the correct program to invoke as the linker has failed and resulted in `None` instead:
```
          File "/tmp/pip-build-env-qpqyblez/overlay/lib/pypy3.8/site-packages/setuptools/_distutils/unixccompiler.py", line 269, in link
            self.linker_exe
        TypeError: 'NoneType' object is not subscriptable (key slice(None, None, None))
        [end of output]
```
Could the problem be inside the version of the build container such as pypy_x86_64: quay.io/pypa/manylinux2014_x86_64:2024.08.03-1 ?

```
commit beb16342b3dd1584e88598bfb92b192ebf90a972
Author: mayeut <mayeut@users.noreply.github.com>
Date:   Sat Jun 8 20:55:20 2024 +0200

    feature: remove PyPy 3.7 & 3.8 from images
```

it looks like pypy 3.8 is built by default, but has been dropped from manylinux. Is cibuildwheel supposed to fetch the toolchain in some alternate way when this happens? I am not able to interpret my build logs to see if this is happening, but I can sure see that in the 2024.08.03-1 image pp3.8 is not there .. but pp3.7 is not either, yet it appearently builds OK.

I hope some of this information might help direct this issue to the correct place. In my project, I'll just be disabling pp* or pp38* wheels and moving on, because I doubt pypy users are important users of my weird little project.

**Comment by henryiii** [comment] 2024-09-17 16:11
This is a bug in PyPy + setuptools interaction, I don't think cibuildwheel is involved at all. PyPy's official stance is PyPy 3.7-3.9 are not supported and are not expected to work. I think 3.7 works because it's getting an old setuptools. I _think_ PyPy's latest (3.10 only) may contain the fix.

If possible, I'd recommend only building PyPy3.10. That's what PyPy recommends. We just don't have a general concept of a "default-off" identifier at the moment.

**Comment by QuLogic** [comment] 2024-09-26 08:30
The setuptools bug is https://github.com/pypa/distutils/issues/283

**Comment by joerick** [comment] 2024-10-27 13:14
Closing as a setuptools issue, see above.

**Closed by joerick** 2024-10-27 13:14 UTC
