### ISSUE TITLE
Building 32-bit wheels on Raspberry Pi OS?

### ISSUE THREAD

**Issue by David00** [pypa/cibuildwheel#1626] opened 2023-09-25 09:36 UTC
### Description

Howdy! I'm stuck and I'm looking for guidance. I've crawled through the docs and FAQ and can't seem to find an answer.

I'm trying to build wheels for my project using a fresh install of Raspberry Pi OS Lite (32-bit) on a new Raspberry Pi 4. My project includes a custom C extension which is why I'm targeting specific architectures.

Here is some information about the hardware and software on this Pi:
```bash
$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

$ uname -a
Linux buildpi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

$ lscpu
Architecture:                    aarch64
Byte Order:                      Little Endian
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
Vendor ID:                       ARM
Model:                           3
Model name:                      Cortex-A72

$ pip freeze | grep cibuild
cibuildwheel==2.16.0
```

I am trying to build wheels for a project of mine which will be used exclusively on other Raspberry Pis - and most commonly on 32-bit Raspberry Pi OS installations.  I thought it would be easiest to build wheels for my target system on a native 32 bit system, but I'm running into this issue: 

> $ cibuildwheel --platform linux --archs native
> ... 
>WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/arm/v8) and no specific platform was requested

I don't see a specific platform available in the list of platform options (output of `cibuildwheel --help`). So, is it not possible to build wheels for a 32-bit ARM operating system using cibuildwheel? I know qemu can be used to build for different architectures than what the host is running, but even still, I don't see anything suggesting that building for arm32 is possible. 

I installed numpy as a test so I could see what wheel Pip chose (since Numpy also uses C extensions):

>  Downloading https://www.piwheels.org/simple/numpy/numpy-1.25.2-cp39-cp39-linux_armv7l.whl

... so I suppose my target architecture should be `armv7`.  I'll have to look into how Numpy creates their wheels.

Thanks!

**Comment by David00** [comment] 2023-09-25 09:39
Well, despite all my searching, I did not see the following issue until after posting: 
https://github.com/pypa/cibuildwheel/issues/1421

I'll leave my issue up for a little bit for discussion.

**Comment by joerick** [comment] 2023-09-25 10:10
Since you're using Raspberry Pi OS, take a look at the [Pi Wheels](https://www.piwheels.org) project. It automatically builds packages that have an sdist on PyPI and makes them available on an additional index.

**Comment by David00** [comment] 2023-10-03 19:36
Thanks for the reference, @joerick. I unfortunately will not be releasing an sdist to the public for this project, so I'm looking for a 100% self-hosted option. [It looks like](https://piwheels.readthedocs.io/en/latest/index.html) I can run my own instance of Piwheels, so I'll start there!

**Comment by joerick** [comment] 2023-10-04 09:34
No worries. Closing as duplicate of https://github.com/pypa/cibuildwheel/issues/1421

**Closed by joerick** 2023-10-04 09:34 UTC
